# Generated by Django 5.2.7 on 2025-12-12 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DicaDeSustentabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dica de Sustentabilidade",
                "verbose_name_plural": "Dicas de Sustentabilidade",
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "dica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.dicadesustentabilidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="RegistroCalculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_calculo",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("distancia", models.FloatField(verbose_name="Distância (km)")),
                (
                    "transporte",
                    models.CharField(max_length=50, verbose_name="Meio de Transporte"),
                ),
                ("co2_emitido", models.FloatField(verbose_name="CO2 Emitido (kg)")),
                ("arvores", models.FloatField(verbose_name="Árvores para compensar")),
                (
                    "custo_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Custo Estimado (R$)",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
