# Generated by Django 5.2.8 on 2025-11-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(help_text="Entre o nome", max_length=100)),
                (
                    "idade",
                    models.IntegerField(
                        blank=True, help_text="Entre a idade", null=True
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Entre o salário",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Informe o email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "dtNasc",
                    models.DateField(
                        blank=True,
                        help_text="Nascimento no formato YYYY-MM-DD",
                        null=True,
                        verbose_name="Data de nascimento",
                    ),
                ),
            ],
        ),
    ]
