# Generated by Django 5.2.7 on 2025-12-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroCalculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distancia", models.FloatField(verbose_name="Distância (km)")),
                (
                    "transporte",
                    models.CharField(max_length=50, verbose_name="Meio de Transporte"),
                ),
                ("co2_emitido", models.FloatField(verbose_name="CO2 Emitido (kg)")),
                ("arvores", models.FloatField(verbose_name="Árvores para compensar")),
                (
                    "data_calculo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Cálculo"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Pessoa",
        ),
    ]
