# Generated by Django 5.2.7 on 2025-12-05 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_registrocalculo_delete_pessoa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DicaDeSustentabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dica de Sustentabilidade",
                "verbose_name_plural": "Dicas de Sustentabilidade",
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "dica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.dicadesustentabilidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_envio"],
            },
        ),
    ]
